# Generated by Django 5.2.6 on 2025-09-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.CharField(blank=True, max_length=255, null=True)),
                ("gm_msgid", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("from_header", models.TextField(blank=True, null=True)),
                ("to_header", models.JSONField(blank=True, null=True)),
                ("cc_header", models.JSONField(blank=True, null=True)),
                ("bcc_header", models.JSONField(blank=True, null=True)),
                ("text_body", models.TextField(blank=True, null=True)),
                ("html_body", models.TextField(blank=True, null=True)),
                ("has_attachment", models.BooleanField(default=False)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
