# Generated by Django 5.2.6 on 2025-09-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("is_valid", models.BooleanField(default=True)),
                ("domain", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("encrypted_password", models.CharField(max_length=255)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="email_accounts", to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpamedMail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spamed_mails",
                        to="email_account.emailaccount",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="emailaccount",
            constraint=models.UniqueConstraint(fields=("user", "priority"), name="uniq_user_priority"),
        ),
        migrations.AddConstraint(
            model_name="spamedmail",
            constraint=models.UniqueConstraint(fields=("account", "address"), name="uniq_spamed_email_per_account"),
        ),
    ]
