# Generated by Django 5.2.6 on 2025-10-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("domain", models.CharField(max_length=255)),
                ("address", models.EmailField(max_length=254, unique=True)),
                ("encrypted_password", models.CharField(max_length=255)),
                (
                    "interests",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="사용자 관심사 목록 (예: ['기술', '스포츠'])",
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.CharField(blank=True, help_text="사용자의 직업", max_length=100, null=True),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True,
                        help_text="계정의 용도 (예: 개인용, 업무용)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpamedMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spamed_mails",
                        to="email_account.emailaccount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "address"),
                        name="uniq_spamed_email_per_account",
                    )
                ],
            },
        ),
    ]
