# Generated by Django 5.2.6 on 2025-09-26 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailaccount",
            old_name="email",
            new_name="address",
        ),
    ]
