# Generated by Django 5.2.8 on 2025-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_account", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="address",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="emailaccount",
            constraint=models.UniqueConstraint(fields=("user", "address"), name="uniq_email_per_user"),
        ),
    ]
