# Generated by Django 5.2.6 on 2025-09-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("email_account", "0001_initial"),
        ("email_content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(max_length=255)),
                (
                    "folder",
                    models.CharField(
                        choices=[("inbox", "Inbox"), ("sent", "Sent"), ("junk", "Junk"), ("starred", "Starred")],
                        default="inbox",
                        max_length=20,
                    ),
                ),
                ("is_important", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("is_summarized", models.BooleanField(default=False)),
                ("summarized_content", models.TextField(blank=True, null=True)),
                ("received_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="email_account.emailaccount",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="email_content.emailcontent",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("account", "email"), name="uniq_account_email")],
            },
        ),
    ]
