# Generated by Django 5.2.6 on 2025-10-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("email_account", "0001_initial"),
        ("email_content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=255)),
                (
                    "folder",
                    models.CharField(
                        choices=[
                            ("inbox", "받은 편지함"),
                            ("sent", "보낸 편지함"),
                            ("spam", "스팸 편지함"),
                            ("starred", "별표 편지함"),
                            ("trash", "휴지통"),
                        ],
                        default="inbox",
                        help_text="폴더 지정: inbox(받은 편지함), sent(보낸 편지함), spam(스팸 메일함), starred(별표 편지함), trash(휴지통)",
                        max_length=20,
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, help_text="중요 메일 표시 여부"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, help_text="상단 고정 여부"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, help_text="읽음 상태 여부"),
                ),
                (
                    "is_summarized",
                    models.BooleanField(default=False, help_text="요약 여부"),
                ),
                ("summarized_content", models.TextField(blank=True, null=True)),
                ("received_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="email_account.emailaccount",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="email_content.emailcontent",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("account", "email"), name="uniq_account_email")],
            },
        ),
    ]
