# Generated by Django 5.2.8 on 2025-11-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmetadata",
            name="is_spammed",
            field=models.BooleanField(default=False, help_text="스팸 메일 여부"),
        ),
    ]
