# Generated by Django 5.2.8 on 2025-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_metadata", "0002_emailmetadata_is_spammed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmetadata",
            name="is_spammed",
            field=models.BooleanField(blank=True, help_text="스팸 메일 여부", null=True),
        ),
    ]
