# Generated by Django 5.2.6 on 2025-09-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("email_account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="email_account.emailaccount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("account", "address"), name="uniq_contact_per_account")
                ],
            },
        ),
    ]
