# Generated by Django 5.2.6 on 2025-09-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='이름')),
                ('email_address', models.EmailField(max_length=254, verbose_name='이메일 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '주소록',
                'verbose_name_plural': '주소록 목록',
            },
        ),
    ]
