# Generated by Django 5.2.6 on 2025-10-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        ("email_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="email_account.emailaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(fields=("account", "address"), name="uniq_contact_per_account"),
        ),
    ]
