# Generated by Django 5.2.6 on 2025-10-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="main_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="template_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
