# Generated by Django 5.2.6 on 2025-11-01 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_account", "0001_initial"),
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="email_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="email_account.emailaccount",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="main_category",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="sub_category",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="template_title",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_content",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
