# Generated by Django 5.2.8 on 2025-11-10 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0002_template_created_at_template_email_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
