"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

############### 테스트용 ###############
from dotenv import load_dotenv

# .env 파일 로드
load_dotenv()
#######################################
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Clerk 사용 안함 환경변수 (테스트용)
CLERK_TURN_OFF = os.environ.get("CLERK_TURN_OFF") == "True"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Local Apps
    "user",
    "email_content",
    "email_account",
    "email_attachment",
    "email_metadata",
    "template",
    "contact",
    # Third-party Apps
    "rest_framework",
    # drf 문서 자동생성용 앱
    "drf_spectacular",
    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Fernet encryption key for EmailAccount passwords
# Loaded from .env file
FERNET_KEY = os.environ.get("FERNET_KEY")

# Django REST Framework & drf-spectacular settings
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "user.auth.ClerkAuthentication",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Mailer API",
    "DESCRIPTION": "Mailer project",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "AUTH_SCHEMA_EXTENSIONS": {
        "test_auth": "user.auth.TestAuthenticationScheme",
    },
    # API 그룹화를 위한 경로 접두사 지정
    "SCHEMA_PATH_PREFIX": r"/api",
    # 각 앱(태그)에 대한 설명 추가
    "TAGS": [
        {"name": "user", "description": "사용자 인증 및 정보 관련 API"},
        {"name": "account", "description": "이메일 계정 연동 및 관리 API"},
        {"name": "email", "description": "통합 메일 조회, 관리 및 요약 API"},
        {"name": "contact", "description": "주소록(즐겨찾기) 관리 API"},
        {"name": "template", "description": "메일 템플릿 관련 API"},
        {"name": "attachment", "description": "첨부파일 관련 API"},
    ],
}

# Clerk 환경변수
# CLERK_ISSUER는 Clerk 대시보드에서 복사
CLERK_ISSUER = "https://<your-clerk-domain>"  # 예: https://example.clerk.accounts.dev
CLERK_JWKS_URL = f"{CLERK_ISSUER}/.well-known/jwks.json"
CLERK_AUDIENCE = None  # Session Token 쓰면 보통 None. JWT Template 쓰면 "my-backend" 등으로 세팅

# SMTP 기본 발신자 이메일 주소
DEFAULT_FROM_EMAIL = os.getenv("SMTP_DEFAULT_SENDER", "no-reply@example.com")

# (선택) 캐시로 멱등성/레이트리밋
CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}


# ####################################################################
# API TEST MODE (Clerk 비활성화)
# ####################################################################
# 사용법: .env 파일에 CLERK_TURN_OFF=True 설정
# 프로덕션 전환 시: 이 블록 전체를 삭제하거나, .env 파일의 값을 False로 바꾸세요.
# ####################################################################
if CLERK_TURN_OFF:
    # 1. 인증 클래스를 Clerk 대신 테스트용 클래스로 변경
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = [
        "user.auth.TestAuthentication",
    ]

#######################################################################


# Celery Settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = "Asia/Seoul"
CELERY_ENABLE_UTC = False

# 주기적 작업 스케줄(Celery Beat)

CELERY_BEAT_SCHEDULE = {
    # 30초마다 스팸 분류 시도
    "classify-unprocessed-email-metadata": {
        "task": "email_metadata.tasks.classify_unprocessed_metadata",
        "schedule": 30.0,  # seconds
        "kwargs": {"batch_size": 30, "sleep": 1.0},
    },
    # 2분마다 큐 상태 로깅
    "log-spam-queue-depth": {
        "task": "email_metadata.tasks.log_spam_queue_depth",
        "schedule": 120.0,
    },
}
