# Generated by Django 5.2.6 on 2025-09-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='제목')),
                ('body', models.TextField(blank=True, null=True, verbose_name='본문')),
                ('from_address', models.EmailField(max_length=254, verbose_name='보낸 사람')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='보낸 시각')),
            ],
            options={
                'verbose_name': '이메일',
                'verbose_name_plural': '이메일 목록',
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(default='inbox', max_length=50, verbose_name='폴더')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요 표시')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='고정')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('is_summarized', models.BooleanField(default=False, verbose_name='요약 여부')),
                ('summarized_content', models.TextField(blank=True, null=True, verbose_name='요약된 내용')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='수신 시각')),
            ],
            options={
                'verbose_name': '메일함',
                'verbose_name_plural': '메일함 목록',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='첨부 파일')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='파일 이름')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='파일 타입')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='파일 크기')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.email', verbose_name='이메일')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일 목록',
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.EmailField(max_length=254, verbose_name='수신 주소')),
                ('recipient_type', models.CharField(choices=[('TO', '받는 사람'), ('CC', '참조'), ('BCC', '숨은 참조')], max_length=3, verbose_name='수신자 유형')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mail.email', verbose_name='이메일')),
            ],
            options={
                'verbose_name': '이메일 수신자',
                'verbose_name_plural': '이메일 수신자 목록',
            },
        ),
    ]
